apiVersion: apps/v1
kind: Deployment
metadata:
  name: pode-deployment-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pode
      version: v1
  template:
    metadata:
      labels:
        app: pode
        version: v1
    spec:
      containers:
        - name: pode-v1
          image: amrelzahar/pode-server:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
